services:
  mariadb: 
    image: mariadb:latest
    volumes:
      - mdb_vol:/var/lib/mysql
      - ./mariadb/scripts:/docker-entrypoint-initdb.d
    ports:
      - "8666:3306"
    networks:
      dockern:
        ipv4_address: 10.0.0.2
    env_file:
      - .env
  nginx:
    build: nginx
    volumes:
      - ./camagru_back:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - "mariadb"
    networks:
      dockern:
        ipv4_address: 10.0.0.3
    restart: on-failure
  
  node_fe_dev:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/styles:/app/styles
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      dockern:
        ipv4_address: 10.0.0.4
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: on-failure
  
  
volumes:
  mdb_vol: {}
networks:
  dockern: 
    ipam:
      config:
        - subnet: 10.0.0.0/29
          gateway: 10.0.0.1

  
